### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nxuv** [artificial-studio/raylight#10]
- [ ] Add Vulkan wrapper
- [ ] Add SDL wrapper
- [ ] ...?
- [ ] Test for needed changes
- [ ] Integrate audio engine (possibly SoLoud)
- [ ] Integrate physics engine (possibly newton)
- [ ] Deferred rendering
- [ ] Make test game (demo asteroids? #7)
